const firebase = require("firebase");
require("firebase/firestore");

// This file is to be executed only once, via node, to create all the databases in FIREBASE

firebase.initializeApp({
  apiKey: "AIzaSyAgGqLFTNItz-HQES7bdJGUcwfWvwQPEDo",
  authDomain: "reactproyect-coderhouse.firebaseapp.com",
  projectId: "reactproyect-coderhouse",
  storageBucket: "reactproyect-coderhouse.appspot.com",
  messagingSenderId: "326791823247",
  appId: "1:326791823247:web:abe746165f98ed30a015fa",
  measurementId: "G-7WPJJKPTQ2",
});

const db = firebase.firestore();

const providers = [
  {
    id: 0,
    name: "Yo te presté",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=YO",
    description: "Préstamos de amigo",
    phone: "800-123-9432",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 1,
    name: "AFIP",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=AFIP",
    description: "AFIP Seti DJ",
    phone: "800-123-9432",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 2,
    name: "AMERICA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=AMERICA",
    description: "BANK OF AMERICA NATIONAL ASSOCIATION",
    phone: "800-123-8824",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 4,
    name: "BBVA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BBVA",
    description: "BANCO BBVA ARGENTINA S.A.",
    phone: "800-123-7476",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 5,
    name: "BICA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BICA",
    description: "BANCO BICA S.A.",
    phone: "800-123-6784",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 7,
    name: "BRUBANK",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BRUBANK",
    description: "BRUBANK S.A.U.",
    phone: "800-123-6752",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 13,
    name: "CHUBUT",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CHUBUT",
    description: "BANCO DEL CHUBUT S.A.",
    phone: "800-123-7186",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 15,
    name: "CITIBANK",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CITIBANK",
    description: "CITIBANK N.A.",
    phone: "800-123-4275",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 23,
    name: "CORDOBA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CORDOBA",
    description: "BANCO DE LA state DE CORDOBA S.A.",
    phone: "800-123-8895",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 25,
    name: "CREDICOOP",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CREDICOOP",
    description: "BANCO CREDICOOP COOPERATIVO LIMITADO",
    phone: "800-123-4021",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 29,
    name: "ENTRE RIOS",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ENTRE RIOS",
    description: "NUEVO BANCO DE ENTRE RIOS S.A.",
    phone: "800-123-7128",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 32,
    name: "FORD",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FORD",
    description: "FORD CREDIT CIA. FINAN. S.A.",
    phone: "800-123-8194",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 33,
    name: "FORMOSA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FORMOSA",
    description: "BANCO DE FORMOSA S.A.",
    phone: "800-123-1970",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 34,
    name: "GALICIA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=GALICIA",
    description: "BANCO DE GALICIA Y BUENOS AIRES S.A.U.",
    phone: "800-123-5954",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 36,
    name: "HIPOTECARIO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=HIPOTECARIO",
    description: "BANCO HIPOTECARIO SA",
    phone: "800-123-6348",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 37,
    name: "HSBC",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=HSBC",
    description: "HSBC BANK ARGENTINA S.A.",
    phone: "800-123-1275",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 38,
    name: "ICBC",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ICBC",
    description: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.",
    phone: "800-123-2070",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 39,
    name: "INDUSTRIAL",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=INDUSTRIAL",
    description: "BANCO INDUSTRIAL S.A.",
    phone: "800-123-7586",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 46,
    name: "MACRO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MACRO",
    description: "BANCO MACRO S.A.",
    phone: "800-123-7015",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 49,
    name: "MERCEDES-BENZ",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=MERCEDES-BENZ",
    description: "MERCEDES-BENZ COMPAÑIA FINANCIERA ARGENTINA S.A.",
    phone: "800-123-3034",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 53,
    name: "NACION",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=NACIÓN",
    description: "BANCO DE LA NACION ARGENTINA",
    phone: "800-123-7044",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 56,
    name: "PATAGONIA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PATAGONIA",
    description: "BANCO PATAGONIA S.A.",
    phone: "800-123-5273",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 63,
    name: "ROMBO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ROMBO",
    description: "ROMBO CIA. FINAN. S.A.",
    phone: "800-123-2440",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 68,
    name: "SANTA FE",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTA FE",
    description: "NUEVO BANCO DE SANTA FE S.A.",
    phone: "800-123-5187",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 69,
    name: "SANTANDER",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTANDER",
    description: "BANCO SANTANDER RIO S.A.",
    phone: "800-123-3200",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 76,
    name: "TOYOTA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=TOYOTA",
    description: "TOYOTA COMPAÑIA FINANCIERA DE ARGENTINA S.A.",
    phone: "800-123-3798",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 78,
    name: "URUGUAY",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=URUGUAY",
    description: "BANCO DE LA REP. ORIENTAL DEL URUGUAY",
    phone: "800-123-2733",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 81,
    name: "VOLKSWAGEN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=VOLKSWAGEN",
    description: "VOLKSWAGEN FINANCIAL SERVICES COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-3887",
    providesCard: false,
    showOnCarousel: false,
  },
];
const users = [
  {
    id: 0,
    name: "Diego",
    surname: "Maradona",
    email: "eldiego@pelo.ta",
    pass: "fafafaYNoDeBootstrap",
    state: "Villa Fiorito",
    city: "Buenos Aires",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 1000000,
    incomeNotRegistered: 100000000,
    fiscalStatus: 1,
    homeOwner: false,
    carOwner: true,
  },
  {
    id: 1,
    name: "Homero",
    surname: "Simpson",
    email: "homero@thesimpsons.com",
    pass: "marge",
    state: "Pensilvania",
    city: "Springfield",
    maritalStatus: 1,
    incomeAsEmployee: 98000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 2,
    name: "Uriel",
    surname: "Levcovich",
    email: "glevcovich@outlook.com",
    pass: "coderhouse",
    state: "Santa Fe",
    city: "Santa Fe",
    maritalStatus: 1,
    incomeAsEmployee: 60000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 20000,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 3,
    name: "Bruce",
    surname: "Waine",
    email: "iam@batman.org",
    pass: "iloverobin",
    state: "Massachusetts",
    city: "Boston",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 25000000,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 4,
    name: "Peter",
    surname: "Parker",
    email: "peterparker@marvel.com",
    pass: "tiamai",
    state: "New York",
    city: "New York",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 20000,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: false,
    carOwner: false,
  },
  {
    id: 5,
    name: "Isidoro",
    surname: "Cañones",
    email: "isidorito@hotmail.com",
    pass: "isidorito",
    state: "CABA",
    city: "CABA",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 2000000,
    fiscalStatus: 1,
    homeOwner: false,
    carOwner: true,
  },
  {
    id: 6,
    name: "Patoruzú",
    surname: "Patoruzú",
    email: "patoruzu@argentina.net",
    pass: "lachacha",
    state: "La Pampa",
    city: "Santa Rosa",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 35000000,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: false,
  },
  {
    id: 7,
    name: "Clark",
    surname: "Kent",
    email: "ckent@theglobe.com",
    pass: "louise",
    state: "New York",
    city: "New York",
    maritalStatus: 0,
    incomeAsEmployee: 80000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: false,
  },
  {
    id: 8,
    name: "El papá de",
    surname: "Mafalda",
    email: "argentinopromedio@ningunlado.com",
    pass: "mafalda",
    state: "CABA",
    city: "CABA",
    maritalStatus: 1,
    incomeAsEmployee: 70000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 9,
    name: "Emilio",
    surname: "Ravenna",
    email: "peretti@lossimuladores.com",
    pass: "MáximoCozzetti",
    state: "CABA",
    city: "CABA",
    maritalStatus: 1,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 200000,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: true,
  },
];
const services = [
  {
    id: 0,
    name: "Descubierto en CC$",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Descubierto",
    description:
      "Tasa de interés aplicable al descubierto de una cuenta corriente en pesos",
    isCredit: true,
  },
  {
    id: 1,
    name: "Saldo de Tarjeta VISA",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=InterésMaster",
    description:
      "Tasa de interés aplicable al saldo impago del resumen de la tarjeta MasterCard",
    isCredit: true,
  },
  {
    id: 2,
    name: "Saldo de Tarjeta Mastercard",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=InterésVisa",
    description:
      "Tasa de interés aplicable al saldo impago del resumen de la tarjeta Visa",
      isCredit: true,
    },
  {
    id: 3,
    name: "Saldo de Tarjeta AMEX",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Crédito",
    description:
      "Tasa de interés aplicable al momento de solicitar un crédito en pesos",
      isCredit: true,
    },
  {
    id: 4,
    name: "Crédito a sola firma",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Crédito",
    description:
      "Tasa de interés aplicable al momento de solicitar un crédito en pesos",
      isCredit: true,
    },
  {
    id: 5,
    name: "Crédito para compras de inmuebles",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Inmuebles",
    description: "Interés variable dependiente de la inflación",
    isCredit: true,
    },
  {
    id: 6,
    name: "Financiación de compra de vehículos",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Descubierto",
    description:
      "Tasa de interés aplicable al descubierto de una cuenta corriente en pesos",
      isCredit: true,
    },
    {id: 7,
    name: "Servicio de telefonía celular",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Celular",
    description:
      "Tarifa plana por el servicio de celular",
      isCredit: false,
    },
    {id: 8,
      name: "Servicio de internet hogareño",
      image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Internet",
      description:
        "Tarifa plana por el servicio de Internet",
        isCredit: false,
      },
      {id: 9,
        name: "Seguro de vida",
        image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Seguro de vida",
        description:
          "Abono mensual por el seguro de vida",
          isCredit: false,
        },
        {id: 10,
          name: "Gasto de mantenimiento de cuenta",
          image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Mantenimiento_cuenta",
          description:
            "Costo mensual por el paquete de productos estandard",
            isCredit: false,
          },
];

providers.forEach(function (i) {
  db.collection("providers")
    .add({
      id: i.id,
      name: i.name,
      image: i.image,
      description: i.description,
      phone: i.phone,
      providesCard: i.providesCard,
      showOnCarousel: i.showOnCarousel,
    })
    .then(function (doc) {})
    .catch(function (error) {
      console.error("Error: ", error);
    });
});

users.forEach(function (i) {
  db.collection("users")
    .add({
      id: i.id,
      name: i.name,
      surname: i.surname,
      email: i.email,
      pass: i.pass,
      state: i.state,
      city: i.city,
      maritalStatus: i.maritalStatus,
      incomeAsEmployee: i.incomeAsEmployee,
      incomeAsSelfEmployed: i.incomeAsSelfEmployed,
      incomeNotRegistered: i.incomeNotRegistered,
      fiscalStatus: i.fiscalStatus,
      homeOwner: i.homeOwner,
      carOwner: i.carOwner,
    })
    .then(function (doc) {})
    .catch(function (error) {
      console.error("Error: ", error);
    });
});

services.forEach(function (i) {
  db.collection("services")
    .add({
      id: i.id,
      name: i.name,
      image: i.image,
      description: i.description,
      isCredit: i.isCredit,
    })
    .then(function (doc) {})
    .catch(function (error) {
      console.error("Error: ", error);
    });
});
