const firebase = require("firebase");
require("firebase/firestore");

firebase.initializeApp({
  apiKey: "AIzaSyAgGqLFTNItz-HQES7bdJGUcwfWvwQPEDo",
  authDomain: "reactproyect-coderhouse.firebaseapp.com",
  projectId: "reactproyect-coderhouse",
  storageBucket: "reactproyect-coderhouse.appspot.com",
  messagingSenderId: "326791823247",
  appId: "1:326791823247:web:abe746165f98ed30a015fa",
  measurementId: "G-7WPJJKPTQ2",
});

const db = firebase.firestore();

const users_services = [
  {
    id: 0,
    idUser: 6,
    idProvider: 77,
    idService: 4,
    date: "23/10/2012",
  },
  {
    id: 1,
    idUser: 2,
    idProvider: 26,
    idService: 0,
    date: "20/2/2019",
  },
  {
    id: 2,
    idUser: 2,
    idProvider: 17,
    idService: 2,
    date: "18/6/2011",
  },
  {
    id: 3,
    idUser: 2,
    idProvider: 59,
    idService: 1,
    date: "26/12/2018",
  },
  {
    id: 4,
    idUser: 9,
    idProvider: 81,
    idService: 0,
    date: "16/11/2012",
  },
  {
    id: 5,
    idUser: 9,
    idProvider: 78,
    idService: 5,
    date: "9/6/2013",
  },
  {
    id: 6,
    idUser: 7,
    idProvider: 3,
    idService: 3,
    date: "20/8/2014",
  },
  {
    id: 7,
    idUser: 9,
    idProvider: 35,
    idService: 2,
    date: "2/9/2015",
  },
  {
    id: 8,
    idUser: 8,
    idProvider: 75,
    idService: 4,
    date: "1/11/2019",
  },
  {
    id: 9,
    idUser: 6,
    idProvider: 2,
    idService: 6,
    date: "14/7/2019",
  },
  {
    id: 10,
    idUser: 4,
    idProvider: 59,
    idService: 4,
    date: "7/2/2015",
  },
  {
    id: 11,
    idUser: 3,
    idProvider: 6,
    idService: 5,
    date: "4/6/2011",
  },
  {
    id: 12,
    idUser: 4,
    idProvider: 15,
    idService: 0,
    date: "29/3/2020",
  },
  {
    id: 13,
    idUser: 1,
    idProvider: 41,
    idService: 6,
    date: "24/2/2013",
  },
  {
    id: 14,
    idUser: 1,
    idProvider: 12,
    idService: 2,
    date: "23/8/2013",
  },
  {
    id: 15,
    idUser: 4,
    idProvider: 19,
    idService: 0,
    date: "12/6/2014",
  },
  {
    id: 16,
    idUser: 6,
    idProvider: 61,
    idService: 2,
    date: "21/4/2018",
  },
  {
    id: 17,
    idUser: 3,
    idProvider: 40,
    idService: 3,
    date: "2/8/2020",
  },
  {
    id: 18,
    idUser: 5,
    idProvider: 60,
    idService: 3,
    date: "2/7/2016",
  },
  {
    id: 19,
    idUser: 7,
    idProvider: 36,
    idService: 3,
    date: "11/1/2010",
  },
  {
    id: 20,
    idUser: 0,
    idProvider: 34,
    idService: 5,
    date: "31/1/2021",
  },
  {
    id: 21,
    idUser: 0,
    idProvider: 38,
    idService: 4,
    date: "23/11/2014",
  },
  {
    id: 22,
    idUser: 6,
    idProvider: 7,
    idService: 1,
    date: "5/5/2013",
  },
  {
    id: 23,
    idUser: 7,
    idProvider: 63,
    idService: 2,
    date: "30/3/2013",
  },
  {
    id: 24,
    idUser: 8,
    idProvider: 9,
    idService: 4,
    date: "5/8/2013",
  },
  {
    id: 25,
    idUser: 8,
    idProvider: 2,
    idService: 6,
    date: "11/8/2015",
  },
  {
    id: 26,
    idUser: 2,
    idProvider: 76,
    idService: 3,
    date: "10/3/2018",
  },
  {
    id: 27,
    idUser: 5,
    idProvider: 64,
    idService: 4,
    date: "8/1/2018",
  },
  {
    id: 28,
    idUser: 9,
    idProvider: 0,
    idService: 3,
    date: "26/8/2014",
  },
  {
    id: 29,
    idUser: 2,
    idProvider: 51,
    idService: 3,
    date: "20/4/2018",
  },
  {
    id: 30,
    idUser: 4,
    idProvider: 63,
    idService: 2,
    date: "7/5/2018",
  },
  {
    id: 31,
    idUser: 1,
    idProvider: 35,
    idService: 6,
    date: "12/8/2010",
  },
  {
    id: 32,
    idUser: 3,
    idProvider: 50,
    idService: 3,
    date: "27/11/2013",
  },
  {
    id: 33,
    idUser: 2,
    idProvider: 41,
    idService: 4,
    date: "4/6/2012",
  },
  {
    id: 34,
    idUser: 9,
    idProvider: 57,
    idService: 0,
    date: "17/1/2013",
  },
  {
    id: 35,
    idUser: 1,
    idProvider: 75,
    idService: 2,
    date: "30/4/2017",
  },
  {
    id: 36,
    idUser: 5,
    idProvider: 16,
    idService: 5,
    date: "6/8/2019",
  },
  {
    id: 37,
    idUser: 8,
    idProvider: 76,
    idService: 0,
    date: "25/11/2015",
  },
  {
    id: 38,
    idUser: 7,
    idProvider: 77,
    idService: 0,
    date: "4/3/2019",
  },
  {
    id: 39,
    idUser: 0,
    idProvider: 43,
    idService: 4,
    date: "13/8/2010",
  },
  {
    id: 40,
    idUser: 8,
    idProvider: 40,
    idService: 2,
    date: "17/3/2013",
  },
  {
    id: 41,
    idUser: 6,
    idProvider: 46,
    idService: 5,
    date: "11/8/2019",
  },
  {
    id: 42,
    idUser: 9,
    idProvider: 21,
    idService: 1,
    date: "13/8/2020",
  },
  {
    id: 43,
    idUser: 3,
    idProvider: 0,
    idService: 3,
    date: "22/1/2014",
  },
  {
    id: 44,
    idUser: 5,
    idProvider: 71,
    idService: 1,
    date: "2/10/2017",
  },
  {
    id: 45,
    idUser: 0,
    idProvider: 68,
    idService: 5,
    date: "29/11/2016",
  },
  {
    id: 46,
    idUser: 4,
    idProvider: 2,
    idService: 2,
    date: "15/6/2014",
  },
  {
    id: 47,
    idUser: 0,
    idProvider: 21,
    idService: 1,
    date: "23/4/2016",
  },
  {
    id: 48,
    idUser: 3,
    idProvider: 70,
    idService: 0,
    date: "9/4/2017",
  },
  {
    id: 49,
    idUser: 9,
    idProvider: 32,
    idService: 4,
    date: "10/9/2019",
  },
  {
    id: 50,
    idUser: 7,
    idProvider: 29,
    idService: 1,
    date: "8/2/2015",
  },
  {
    id: 51,
    idUser: 7,
    idProvider: 58,
    idService: 3,
    date: "25/6/2019",
  },
  {
    id: 52,
    idUser: 8,
    idProvider: 17,
    idService: 2,
    date: "9/1/2021",
  },
  {
    id: 53,
    idUser: 2,
    idProvider: 1,
    idService: 0,
    date: "28/9/2011",
  },
  {
    id: 54,
    idUser: 8,
    idProvider: 12,
    idService: 4,
    date: "10/1/2014",
  },
  {
    id: 55,
    idUser: 6,
    idProvider: 40,
    idService: 4,
    date: "7/11/2016",
  },
  {
    id: 56,
    idUser: 9,
    idProvider: 25,
    idService: 6,
    date: "27/10/2010",
  },
  {
    id: 57,
    idUser: 0,
    idProvider: 26,
    idService: 4,
    date: "7/4/2018",
  },
  {
    id: 58,
    idUser: 3,
    idProvider: 32,
    idService: 1,
    date: "22/6/2017",
  },
  {
    id: 59,
    idUser: 0,
    idProvider: 68,
    idService: 4,
    date: "3/7/2013",
  },
  {
    id: 60,
    idUser: 5,
    idProvider: 28,
    idService: 5,
    date: "10/7/2018",
  },
  {
    id: 61,
    idUser: 1,
    idProvider: 28,
    idService: 4,
    date: "17/8/2017",
  },
  {
    id: 62,
    idUser: 6,
    idProvider: 44,
    idService: 1,
    date: "13/12/2012",
  },
  {
    id: 63,
    idUser: 6,
    idProvider: 67,
    idService: 5,
    date: "26/11/2012",
  },
  {
    id: 64,
    idUser: 9,
    idProvider: 25,
    idService: 2,
    date: "23/8/2020",
  },
  {
    id: 65,
    idUser: 5,
    idProvider: 77,
    idService: 4,
    date: "26/2/2013",
  },
  {
    id: 66,
    idUser: 7,
    idProvider: 69,
    idService: 5,
    date: "17/2/2014",
  },
  {
    id: 67,
    idUser: 1,
    idProvider: 14,
    idService: 4,
    date: "23/7/2014",
  },
  {
    id: 68,
    idUser: 4,
    idProvider: 18,
    idService: 2,
    date: "7/3/2018",
  },
  {
    id: 69,
    idUser: 8,
    idProvider: 26,
    idService: 6,
    date: "25/1/2019",
  },
  {
    id: 70,
    idUser: 6,
    idProvider: 43,
    idService: 6,
    date: "31/5/2020",
  },
  {
    id: 71,
    idUser: 1,
    idProvider: 38,
    idService: 4,
    date: "18/10/2015",
  },
  {
    id: 72,
    idUser: 9,
    idProvider: 73,
    idService: 2,
    date: "22/11/2015",
  },
  {
    id: 73,
    idUser: 2,
    idProvider: 8,
    idService: 4,
    date: "18/6/2018",
  },
  {
    id: 74,
    idUser: 7,
    idProvider: 50,
    idService: 4,
    date: "15/11/2011",
  },
  {
    id: 75,
    idUser: 7,
    idProvider: 6,
    idService: 5,
    date: "13/2/2014",
  },
  {
    id: 76,
    idUser: 4,
    idProvider: 75,
    idService: 0,
    date: "26/7/2011",
  },
  {
    id: 77,
    idUser: 2,
    idProvider: 37,
    idService: 6,
    date: "25/11/2020",
  },
  {
    id: 78,
    idUser: 7,
    idProvider: 70,
    idService: 3,
    date: "29/11/2013",
  },
  {
    id: 79,
    idUser: 2,
    idProvider: 23,
    idService: 1,
    date: "2/6/2014",
  },
  {
    id: 80,
    idUser: 0,
    idProvider: 54,
    idService: 5,
    date: "9/1/2021",
  },
  {
    id: 81,
    idUser: 3,
    idProvider: 44,
    idService: 5,
    date: "26/5/2011",
  },
  {
    id: 82,
    idUser: 8,
    idProvider: 3,
    idService: 6,
    date: "24/6/2016",
  },
  {
    id: 83,
    idUser: 9,
    idProvider: 79,
    idService: 1,
    date: "11/1/2013",
  },
  {
    id: 84,
    idUser: 5,
    idProvider: 2,
    idService: 5,
    date: "22/7/2013",
  },
  {
    id: 85,
    idUser: 9,
    idProvider: 24,
    idService: 1,
    date: "1/5/2011",
  },
  {
    id: 86,
    idUser: 5,
    idProvider: 15,
    idService: 6,
    date: "8/8/2020",
  },
  {
    id: 87,
    idUser: 6,
    idProvider: 58,
    idService: 2,
    date: "31/10/2019",
  },
  {
    id: 88,
    idUser: 7,
    idProvider: 19,
    idService: 3,
    date: "26/11/2012",
  },
  {
    id: 89,
    idUser: 4,
    idProvider: 12,
    idService: 1,
    date: "27/5/2018",
  },
  {
    id: 90,
    idUser: 9,
    idProvider: 6,
    idService: 5,
    date: "10/5/2015",
  },
  {
    id: 91,
    idUser: 9,
    idProvider: 66,
    idService: 3,
    date: "4/7/2018",
  },
  {
    id: 92,
    idUser: 7,
    idProvider: 69,
    idService: 5,
    date: "15/3/2011",
  },
  {
    id: 93,
    idUser: 3,
    idProvider: 52,
    idService: 5,
    date: "14/6/2016",
  },
  {
    id: 94,
    idUser: 4,
    idProvider: 46,
    idService: 1,
    date: "11/8/2015",
  },
  {
    id: 95,
    idUser: 9,
    idProvider: 72,
    idService: 3,
    date: "20/3/2019",
  },
  {
    id: 96,
    idUser: 9,
    idProvider: 23,
    idService: 1,
    date: "4/4/2010",
  },
  {
    id: 97,
    idUser: 3,
    idProvider: 76,
    idService: 5,
    date: "8/6/2015",
  },
  {
    id: 98,
    idUser: 6,
    idProvider: 73,
    idService: 0,
    date: "20/3/2015",
  },
  {
    id: 99,
    idUser: 0,
    idProvider: 0,
    idService: 3,
    date: "15/11/2020",
  },
];
const providers = [
  {
    id: 0,
    name: "Yo te presté",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=YO",
    description: "Préstamos de amigo",
    phone: "800-123-9432",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 1,
    name: "AFIP",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=AFIP",
    description: "AFIP Seti DJ",
    phone: "800-123-9432",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 2,
    name: "AMERICA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=AMERICA",
    description: "BANK OF AMERICA NATIONAL ASSOCIATION",
    phone: "800-123-8824",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 3,
    name: "BACS",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BACS",
    description: "BACS BANCO DE CREDITO Y SECURITIZACION S.A.",
    phone: "800-123-3657",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 4,
    name: "BBVA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BBVA",
    description: "BANCO BBVA ARGENTINA S.A.",
    phone: "800-123-7476",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 5,
    name: "BICA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BICA",
    description: "BANCO BICA S.A.",
    phone: "800-123-6784",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 6,
    name: "BRADESCO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BRADESCO",
    description: "BANCO BRADESCO ARGENTINA SA",
    phone: "800-123-7785",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 7,
    name: "BRUBANK",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BRUBANK",
    description: "BRUBANK S.A.U.",
    phone: "800-123-6752",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 8,
    name: "state",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=BUENOS AIRES",
    description: "BANCO DE LA state DE BUENOS AIRES",
    phone: "800-123-9081",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 9,
    name: "CENTRAL",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CENTRAL",
    description: "CENTRAL DE LA REPUBLICA ARGENTINA",
    phone: "800-123-7331",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 10,
    name: "CETELEM",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CETELEM",
    description: "BANCO CETELEM ARGENTINA S.A.",
    phone: "800-123-3802",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 11,
    name: "CHACO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CHACO",
    description: "NUEVO BANCO DEL CHACO S.A.",
    phone: "800-123-7524",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 12,
    name: "CHINA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CHINA",
    description: "BANK OF CHINA LIMITED, SUCURSAL BUENOS AIRES",
    phone: "800-123-2227",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 13,
    name: "CHUBUT",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CHUBUT",
    description: "BANCO DEL CHUBUT S.A.",
    phone: "800-123-7186",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 14,
    name: "CIENCIAS ECONOMICAS",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=CIENCIAS ECONOMICAS",
    description: "CONSEJO PROFESIONAL DE CIENCIAS ECONOMICAS DE CABA",
    phone: "800-123-8062",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 15,
    name: "CITIBANK",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CITIBANK",
    description: "CITIBANK N.A.",
    phone: "800-123-4275",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 16,
    name: "city",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=city",
    description: "BANCO DE LA city DE BUENOS AIRES",
    phone: "800-123-4070",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 17,
    name: "CMF",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CMF",
    description: "BANCO CMF S.A.",
    phone: "800-123-4791",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 18,
    name: "COINAG",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=COINAG",
    description: "BANCO COINAG S.A.",
    phone: "800-123-6748",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 19,
    name: "COLUMBIA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=COLUMBIA",
    description: "BANCO COLUMBIA S.A.",
    phone: "800-123-5801",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 20,
    name: "COMAFI",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=COMAFI",
    description: "BANCO COMAFI S.A.",
    phone: "800-123-9043",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 21,
    name: "COMERCIO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=COMERCIO",
    description: "BANCO DE COMERCIO S.A.",
    phone: "800-123-6839",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 22,
    name: "CORDIAL",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CORDIAL",
    description: "CORDIAL COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-7757",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 23,
    name: "CORDOBA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CORDOBA",
    description: "BANCO DE LA state DE CORDOBA S.A.",
    phone: "800-123-8895",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 24,
    name: "CORRIENTES",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CORRIENTES",
    description: "BANCO DE CORRIENTES S.A.",
    phone: "800-123-9298",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 25,
    name: "CREDICOOP",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=CREDICOOP",
    description: "BANCO CREDICOOP COOPERATIVO LIMITADO",
    phone: "800-123-4021",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 26,
    name: "CREDITO REGIONAL",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=CREDITO REGIONAL",
    description: "CREDITO REGIONAL COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-6679",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 27,
    name: "DEL SOL",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=DEL SOL",
    description: "BANCO DEL SOL S.A.",
    phone: "800-123-2610",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 28,
    name: "DINO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=DINO",
    description: "BANCO DINO S.A.",
    phone: "800-123-8867",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 29,
    name: "ENTRE RIOS",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ENTRE RIOS",
    description: "NUEVO BANCO DE ENTRE RIOS S.A.",
    phone: "800-123-7128",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 30,
    name: "FCA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FCA",
    description: "FCA Compañía Financiera S.A.",
    phone: "800-123-8547",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 31,
    name: "FINANCIERA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FINANCIERA",
    description: "COMPAÑIA FINANCIERA ARGENTINA S.A.",
    phone: "800-123-7806",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 32,
    name: "FORD",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FORD",
    description: "FORD CREDIT CIA. FINAN. S.A.",
    phone: "800-123-8194",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 33,
    name: "FORMOSA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=FORMOSA",
    description: "BANCO DE FORMOSA S.A.",
    phone: "800-123-1970",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 34,
    name: "GALICIA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=GALICIA",
    description: "BANCO DE GALICIA Y BUENOS AIRES S.A.U.",
    phone: "800-123-5954",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 35,
    name: "GPAT",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=GPAT",
    description: "GPAT COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-5907",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 36,
    name: "HIPOTECARIO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=HIPOTECARIO",
    description: "BANCO HIPOTECARIO SA",
    phone: "800-123-6348",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 37,
    name: "HSBC",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=HSBC",
    description: "HSBC BANK ARGENTINA S.A.",
    phone: "800-123-1275",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 38,
    name: "ICBC",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ICBC",
    description: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.",
    phone: "800-123-2070",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 39,
    name: "INDUSTRIAL",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=INDUSTRIAL",
    description: "BANCO INDUSTRIAL S.A.",
    phone: "800-123-7586",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 40,
    name: "INTERFINANZAS",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=INTERFINANZAS",
    description: "BANCO INTERFINANZAS S.A.",
    phone: "800-123-5554",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 41,
    name: "INVERSIÓN Y COMERCIO EXTERIOR",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=INVERSIÓN Y COMERCIO EXTERIOR",
    description: "BANCO DE INVERSION Y COMERCIO EXTERIOR S.A.",
    phone: "800-123-1778",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 42,
    name: "ITAU",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ITAU",
    description: "BANCO ITAU ARGENTINA S.A.",
    phone: "800-123-9024",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 43,
    name: "JOHN DEERE",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=JOHN DEERE",
    description: "JOHN DEERE CREDIT CIA. FINAN. S.A.",
    phone: "800-123-7325",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 44,
    name: "JULIO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=JULIO",
    description: "BANCO JULIO S.A.",
    phone: "800-123-2776",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 45,
    name: "LA PAMPA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=LA PAMPA",
    description: "BANCO DE LA PAMPA SOCIEDAD DE ECONOMIA MIXTA",
    phone: "800-123-7125",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 46,
    name: "MACRO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MACRO",
    description: "BANCO MACRO S.A.",
    phone: "800-123-7015",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 47,
    name: "MARIVA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MARIVA",
    description: "BANCO MARIVA S.A.",
    phone: "800-123-9643",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 48,
    name: "MAS VENTAS",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MAS VENTAS",
    description: "MAS VENTAS S.A.",
    phone: "800-123-1181",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 49,
    name: "MERCEDES-BENZ",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=MERCEDES-BENZ",
    description: "MERCEDES-BENZ COMPAÑIA FINANCIERA ARGENTINA S.A.",
    phone: "800-123-3034",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 50,
    name: "MERIDIAN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MERIDIAN",
    description: "BANCO MERIDIAN S.A.",
    phone: "800-123-9940",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 51,
    name: "MONTEMAR",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MONTEMAR",
    description: "MONTEMAR CIA. FINAN. S.A.",
    phone: "800-123-6923",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 52,
    name: "MORGAN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=MORGAN",
    description: "JP MORGAN CHASE BANK NA (SUCURSAL BUENOS AIRES)",
    phone: "800-123-4294",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 53,
    name: "NACION",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=NACIÓN",
    description: "BANCO DE LA NACION ARGENTINA",
    phone: "800-123-7044",
    providesCard: true,
    showOnCarousel: true,
  },
  {
    id: 54,
    name: "NEUQUEN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=NEUQUEN",
    description: "BANCO state DEL NEUQUEN S.A.",
    phone: "800-123-2676",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 55,
    name: "PARIBAS",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PARIBAS",
    description: "BNP PARIBAS",
    phone: "800-123-1423",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 56,
    name: "PATAGONIA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PATAGONIA",
    description: "BANCO PATAGONIA S.A.",
    phone: "800-123-5273",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 57,
    name: "PIANO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PIANO",
    description: "BANCO PIANO S.A.",
    phone: "800-123-8384",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 58,
    name: "PROVINCANJE",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PROVINCANJE",
    description: "PROVINCANJE SOCIEDAD ANONIMA",
    phone: "800-123-6917",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 59,
    name: "PSA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=PSA",
    description: "PSA FINANCE ARGENTINA CIA. FINAN. S.A.",
    phone: "800-123-2082",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 60,
    name: "RCI",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=RCI",
    description: "RCI BANQUE S.A.",
    phone: "800-123-3106",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 61,
    name: "RIOJA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=RIOJA",
    description: "BANCO RIOJA SOCIEDAD ANÓNIMA UNIPERSONAL",
    phone: "800-123-7852",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 62,
    name: "ROELA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ROELA",
    description: "BANCO ROELA S.A.",
    phone: "800-123-8392",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 63,
    name: "ROMBO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ROMBO",
    description: "ROMBO CIA. FINAN. S.A.",
    phone: "800-123-2440",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 64,
    name: "ROSARIO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=ROSARIO",
    description: "BANCO MUNICIPAL DE ROSARIO",
    phone: "800-123-8293",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 65,
    name: "SAENZ",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SAENZ",
    description: "BANCO SAENZ S.A.",
    phone: "800-123-9459",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 66,
    name: "SAN JUAN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SAN JUAN",
    description: "BANCO DE SAN JUAN S.A.",
    phone: "800-123-6276",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 67,
    name: "SANTA CRUZ",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTA CRUZ",
    description: "BANCO DE SANTA CRUZ S.A.",
    phone: "800-123-6400",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 68,
    name: "SANTA FE",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTA FE",
    description: "NUEVO BANCO DE SANTA FE S.A.",
    phone: "800-123-5187",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 69,
    name: "SANTANDER",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTANDER",
    description: "BANCO SANTANDER RIO S.A.",
    phone: "800-123-3200",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 70,
    name: "SANTIAGO DEL ESTERO",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=SANTIAGO DEL ESTERO",
    description: "BANCO DE SANTIAGO DEL ESTERO S.A.",
    phone: "800-123-4323",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 71,
    name: "SERVICIOS FINANCIEROS",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=SERVICIOS FINANCIEROS",
    description: "BANCO DE SERVICIOS FINANCIEROS S.A.",
    phone: "800-123-1034",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 72,
    name: "SERVICIOS Y TRANSACCIONES",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=SERVICIOS Y TRANSACCIONES",
    description: "BANCO DE SERVICIOS Y TRANSACCIONES S.A.",
    phone: "800-123-8640",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 73,
    name: "SUCREDITO",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SUCREDITO",
    description: "BANCO SUCREDITO S.A.",
    phone: "800-123-4614",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 74,
    name: "SUPERVIELLE",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=SUPERVIELLE",
    description: "BANCO SUPERVIELLE S.A.",
    phone: "800-123-8552",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 75,
    name: "TIERRA DEL FUEGO",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=TIERRA DEL FUEGO",
    description: "BANCO state DE TIERRA DEL FUEGO",
    phone: "800-123-8160",
    providesCard: true,
    showOnCarousel: false,
  },
  {
    id: 76,
    name: "TOYOTA",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=TOYOTA",
    description: "TOYOTA COMPAÑIA FINANCIERA DE ARGENTINA S.A.",
    phone: "800-123-3798",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 77,
    name: "TRANSATLANTICA",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=TRANSATLANTICA",
    description: "TRANSATLANTICA COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-6215",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 78,
    name: "URUGUAY",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=URUGUAY",
    description: "BANCO DE LA REP. ORIENTAL DEL URUGUAY",
    phone: "800-123-2733",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 79,
    name: "VALORES",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=VALORES",
    description: "BANCO DE VALORES S.A.",
    phone: "800-123-4061",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 80,
    name: "VOII",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=VOII",
    description: "BANCO VOII S.A.",
    phone: "800-123-8021",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 81,
    name: "VOLKSWAGEN",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=VOLKSWAGEN",
    description: "VOLKSWAGEN FINANCIAL SERVICES COMPAÑIA FINANCIERA S.A.",
    phone: "800-123-3887",
    providesCard: false,
    showOnCarousel: false,
  },
  {
    id: 82,
    name: "WILOBANK",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=WILOBANK",
    description: "WILOBANK S.A.",
    phone: "800-123-2677",
    providesCard: true,
    showOnCarousel: false,
  },
];
const users = [
  {
    id: 0,
    name: "Diego",
    surname: "Maradona",
    email: "eldiego@pelo.ta",
    pass: "fafafaYNoDeBootstrap",
    state: "Villa Fiorito",
    city: "Buenos Aires",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 1000000,
    incomeNotRegistered: 100000000,
    fiscalStatus: 1,
    homeOwner: false,
    carOwner: true,
  },
  {
    id: 1,
    name: "Homero",
    surname: "Simpson",
    email: "homero@thesimpsons.com",
    pass: "marge",
    state: "Pensilvania",
    city: "Springfield",
    maritalStatus: 1,
    incomeAsEmployee: 98000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 2,
    name: "Uriel",
    surname: "Levcovich",
    email: "glevcovich@outlook.com",
    pass: "coderhouse",
    state: "Santa Fe",
    city: "Santa Fe",
    maritalStatus: 1,
    incomeAsEmployee: 60000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 20000,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 3,
    name: "Bruce",
    surname: "Waine",
    email: "iam@batman.org",
    pass: "iloverobin",
    state: "Massachusetts",
    city: "Boston",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 25000000,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 4,
    name: "Peter",
    surname: "Parker",
    email: "peterparker@marvel.com",
    pass: "tiamai",
    state: "New York",
    city: "New York",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 20000,
    incomeNotRegistered: 0,
    fiscalStatus: 0,
    homeOwner: false,
    carOwner: false,
  },
  {
    id: 5,
    name: "Isidoro",
    surname: "Cañones",
    email: "isidorito@hotmail.com",
    pass: "isidorito",
    state: "CABA",
    city: "CABA",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 2000000,
    fiscalStatus: 1,
    homeOwner: false,
    carOwner: true,
  },
  {
    id: 6,
    name: "Patoruzú",
    surname: "Patoruzú",
    email: "patoruzu@argentina.net",
    pass: "lachacha",
    state: "La Pampa",
    city: "Santa Rosa",
    maritalStatus: 0,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 35000000,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: false,
  },
  {
    id: 7,
    name: "Clark",
    surname: "Kent",
    email: "ckent@theglobe.com",
    pass: "louise",
    state: "New York",
    city: "New York",
    maritalStatus: 0,
    incomeAsEmployee: 80000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: false,
  },
  {
    id: 8,
    name: "El papá de",
    surname: "Mafalda",
    email: "argentinopromedio@ningunlado.com",
    pass: "mafalda",
    state: "CABA",
    city: "CABA",
    maritalStatus: 1,
    incomeAsEmployee: 70000,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 0,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: true,
  },
  {
    id: 9,
    name: "Emilio",
    surname: "Ravenna",
    email: "peretti@lossimuladores.com",
    pass: "MáximoCozzetti",
    state: "CABA",
    city: "CABA",
    maritalStatus: 1,
    incomeAsEmployee: 0,
    incomeAsSelfEmployed: 0,
    incomeNotRegistered: 200000,
    fiscalStatus: 1,
    homeOwner: true,
    carOwner: true,
  },
];
const services = [
  {
    id: 0,
    name: "Descubierto en CC$",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Descubierto",
    description:
      "Tasa de interés aplicable al descubierto de una cuenta corriente en pesos",
  },
  {
    id: 1,
    name: "Saldo de Tarjeta VISA",
    image:
      "https://dummyimage.com/300x300/9675cd/522da8.png&text=InterésMaster",
    description:
      "Tasa de interés aplicable al saldo impago del resumen de la tarjeta MasterCard",
  },
  {
    id: 2,
    name: "Saldo de Tarjeta Mastercard",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=InterésVisa",
    description:
      "Tasa de interés aplicable al saldo impago del resumen de la tarjeta Visa",
  },
  {
    id: 3,
    name: "Saldo de Tarjeta AMEX",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Crédito",
    description:
      "Tasa de interés aplicable al momento de solicitar un crédito en pesos",
  },
  {
    id: 4,
    name: "Crédito a sola firma",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Crédito",
    description:
      "Tasa de interés aplicable al momento de solicitar un crédito en pesos",
  },
  {
    id: 5,
    name: "Crédito para compras de inmuebles",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Inmuebles",
    description: "Interés variable dependiente de la inflación",
  },
  {
    id: 6,
    name: "Financiación de compra de vehículos",
    image: "https://dummyimage.com/300x300/9675cd/522da8.png&text=Descubierto",
    description:
      "Tasa de interés aplicable al descubierto de una cuenta corriente en pesos",
  },
];

users_services.forEach(function (i) {
  db.collection("users_services")
    .add({
      id: i.id,
      idUser: i.idUser,
      idProvider: i.idProvider,
      idService: i.idService,
      date: i.date,
    })
    .then(function (doc) {
      console.log("users_services id:", doc.id);
    })
    .catch(function (error) {
      console.error("Error: ", error);
    });
});

providers.forEach(function (i) {
  db.collection("providers")
    .add({
      id: i.id,
      name: i.name,
      image: i.image,
      description: i.description,
      phone: i.phone,
      providesCard: i.providesCard,
      showOnCarousel: i.showOnCarousel,
    })
    .then(function (doc) {
      console.log("provider id:", doc.id);
    })
    .catch(function (error) {
      console.error("Error: ", error);
    });
});

users.forEach(function (i) {
  db.collection("users")
    .add({
      id: i.id,
      name: i.name,
      surname: i.surname,
      email: i.email,
      pass: i.pass,
      state: i.state,
      city: i.city,
      maritalStatus: i.maritalStatus,
      incomeAsEmployee: i.incomeAsEmployee,
      incomeAsSelfEmployed: i.incomeAsSelfEmployed,
      incomeNotRegistered: i.incomeNotRegistered,
      fiscalStatus: i.fiscalStatus,
      homeOwner: i.homeOwner,
      carOwner: i.carOwner,
    })
    .then(function (doc) {
      console.log("user id:", doc.id);
    })
    .catch(function (error) {
      console.error("Error: ", error);
    });
});

services.forEach(function (i) {
  db.collection("services")
    .add({
      id: i.id,
      name: i.name,
      image: i.image,
      description: i.description,
    })
    .then(function (doc) {
      console.log("service id:", doc.id);
    })
    .catch(function (error) {
      console.error("Error: ", error);
    });
});
